"""add_gst_seller_fields_to_tax_invoices

Revision ID: 005842b3dca5
Revises: 7cbdfd7c3418
Create Date: 2026-08-17 00:43:26.604157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '005842b3dca5'
down_revision: Union[str, None] = '7cbdfd7c3418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_invoices', sa.Column('hsn_code', sa.String(length=20), nullable=True))
    op.add_column('tax_invoices', sa.Column('taxable_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tax_invoices', sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('tax_invoices', sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tax_invoices', sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('tax_invoices', sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tax_invoices', sa.Column('total_tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tax_invoices', sa.Column('round_off', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_trade_name', sa.String(length=200), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_address', sa.Text(), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_gstin', sa.String(length=15), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_state', sa.String(length=100), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_state_code', sa.String(length=5), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_email', sa.String(length=256), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_bank_name', sa.String(length=100), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_bank_account', sa.String(length=30), nullable=True))
    op.add_column('tax_invoices', sa.Column('seller_bank_ifsc', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_invoices', 'seller_bank_ifsc')
    op.drop_column('tax_invoices', 'seller_bank_account')
    op.drop_column('tax_invoices', 'seller_bank_name')
    op.drop_column('tax_invoices', 'seller_email')
    op.drop_column('tax_invoices', 'seller_state_code')
    op.drop_column('tax_invoices', 'seller_state')
    op.drop_column('tax_invoices', 'seller_gstin')
    op.drop_column('tax_invoices', 'seller_address')
    op.drop_column('tax_invoices', 'seller_trade_name')
    op.drop_column('tax_invoices', 'round_off')
    op.drop_column('tax_invoices', 'total_tax_amount')
    op.drop_column('tax_invoices', 'sgst_amount')
    op.drop_column('tax_invoices', 'sgst_rate')
    op.drop_column('tax_invoices', 'cgst_amount')
    op.drop_column('tax_invoices', 'cgst_rate')
    op.drop_column('tax_invoices', 'taxable_value')
    op.drop_column('tax_invoices', 'hsn_code')
    # ### end Alembic commands ###
