"""add_upi_ocr_fields_buyers_tax_invoices

Revision ID: 7cbdfd7c3418
Revises: f6618cf1b176
Create Date: 2026-08-17 00:39:01.803736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7cbdfd7c3418'
down_revision: Union[str, None] = 'f6618cf1b176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('pin', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyers_order_id'), 'buyers', ['order_id'], unique=True)
    op.create_table('tax_invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('buyer_name', sa.String(length=256), nullable=False),
    sa.Column('buyer_address', sa.Text(), nullable=False),
    sa.Column('buyer_district', sa.String(length=100), nullable=False),
    sa.Column('buyer_pin', sa.String(length=10), nullable=False),
    sa.Column('buyer_state', sa.String(length=100), nullable=False),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(length=256), nullable=False),
    sa.Column('customer_email', sa.String(length=256), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('upi_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('upi_to', sa.String(length=200), nullable=True),
    sa.Column('upi_from', sa.String(length=200), nullable=True),
    sa.Column('upi_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('upi_date', sa.String(length=50), nullable=True),
    sa.Column('upi_time', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('seller_name', sa.String(length=200), nullable=False),
    sa.Column('seller_upi_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_tax_invoices_order_id'), 'tax_invoices', ['order_id'], unique=True)
    op.add_column('payments', sa.Column('upi_to', sa.String(length=200), nullable=True))
    op.add_column('payments', sa.Column('upi_from', sa.String(length=200), nullable=True))
    op.add_column('payments', sa.Column('upi_date', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('upi_time', sa.String(length=50), nullable=True))
    op.alter_column('payments', 'upi_ref',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'upi_ref',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('payments', 'upi_time')
    op.drop_column('payments', 'upi_date')
    op.drop_column('payments', 'upi_from')
    op.drop_column('payments', 'upi_to')
    op.drop_index(op.f('ix_tax_invoices_order_id'), table_name='tax_invoices')
    op.drop_table('tax_invoices')
    op.drop_index(op.f('ix_buyers_order_id'), table_name='buyers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
