"""add_payment_proof_ocr_columns

Revision ID: f6618cf1b176
Revises: ee0a085a29ef
Create Date: 2026-08-16 18:22:39.278617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f6618cf1b176'
down_revision: Union[str, None] = 'ee0a085a29ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('screenshot_b64', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('ocr_text', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('ocr_amount_detected', sa.Boolean(), nullable=False))
    op.add_column('payments', sa.Column('upi_ref', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'upi_ref')
    op.drop_column('payments', 'ocr_amount_detected')
    op.drop_column('payments', 'ocr_text')
    op.drop_column('payments', 'screenshot_b64')
    # ### end Alembic commands ###
